# Generated by Django 5.2.17 on 2026-09-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_followers', models.PositiveIntegerField(default=100000)),
                ('facebook_followers', models.PositiveIntegerField(default=98000)),
                ('youtube_subscribers', models.PositiveIntegerField(default=67000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
