# Generated by Django 5.2.17 on 2026-09-04 13:19

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_reel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reel',
            name='video',
            field=models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='reels/'),
        ),
    ]
