# Generated by Django 5.2.17 on 2026-09-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_reel_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='youtube_subscribers',
        ),
        migrations.AddField(
            model_name='about',
            name='youtube_followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='about',
            name='facebook_followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='about',
            name='instagram_followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cities',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='projects',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='years',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
