# Generated by Django 5.2.17 on 2026-09-02 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('type', models.CharField(choices=[('architecture', 'Architecture'), ('interior', 'Interior')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('plot_area', models.CharField(blank=True, max_length=100)),
                ('built_up_area', models.CharField(blank=True, max_length=100)),
                ('carpet_area', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('upcoming', 'Upcoming')], default='completed', max_length=20)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='projects/banners/')),
                ('banner_position', models.CharField(blank=True, default='center', max_length=100)),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='projects/cards/')),
                ('card_image_position', models.CharField(blank=True, default='center', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('position', models.CharField(blank=True, default='center center', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='projects.project')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
