# Generated by Django 5.2.17 on 2026-09-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_consultation_workinghours_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='banner_image_original',
            field=models.ImageField(blank=True, null=True, upload_to='projects/originals/banners/'),
        ),
        migrations.AddField(
            model_name='project',
            name='card_image_original',
            field=models.ImageField(blank=True, null=True, upload_to='projects/originals/cards/'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/originals/gallery/'),
        ),
    ]
