# Generated by Django 5.2.17 on 2026-09-17 12:59

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_banner_image_original_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='banner_image_original',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\HP\\Desktop\\MainGouravKalaArchitects\\GouravKalaArchitectsBackend\\media\\project-originals'), upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='card_image_original',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\HP\\Desktop\\MainGouravKalaArchitects\\GouravKalaArchitectsBackend\\media\\project-originals'), upload_to='cards/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='original_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\HP\\Desktop\\MainGouravKalaArchitects\\GouravKalaArchitectsBackend\\media\\project-originals'), upload_to='gallery/'),
        ),
    ]
