# Generated by Django 5.2.17 on 2026-09-25 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_blockedslot'),
        ('projects', '0005_alter_project_banner_image_original_and_more'),
    ]

    operations = [
    ]
