# Generated by Django 5.2.17 on 2026-10-08 12:55

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_merge_20260925_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='banner_image_original',
            field=models.ImageField(blank=True, null=True, storage=projects.models.original_storage, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='card_image_original',
            field=models.ImageField(blank=True, null=True, storage=projects.models.original_storage, upload_to='cards/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='original_image',
            field=models.ImageField(blank=True, null=True, storage=projects.models.original_storage, upload_to='gallery/'),
        ),
    ]
